### ISSUE TITLE
控制台打印列表出现中文时出现偏移

### ISSUE THREAD

**Issue by 553234736** [clyoudu/clyoudu-util#1]

**Comment by clyoudu** [comment]
### 问题原因
在等宽字体中，中文长度为两个字符，英文长度为一个字符，但直接使用String.length()方法时，一个中文仍然返回一个字符

### 解决方案
不使用String.length()获取字符串长度，而是使用字符区间判断是否为大字符集，然后决定该字符长度，详见[StringPadUtil.java](https://github.com/clyoudu/clyoudu-util/blob/master/src/main/java/github/clyoudu/consoletable/util/StringPadUtil.java)

### commit
[Chinese support.](https://github.com/clyoudu/clyoudu-util/commit/4c69ddd90cc7c89d9c14a29ced8b8b0432756bc5)

### 注意
控制台字体必须设置成包含中英文字符集的等宽字体(幼圆等)：
![console_youyuan](https://github.com/clyoudu/clyoudu-util/blob/master/screenshot/console_youyuan.PNG?raw=true)
如果设置成只有英文字符集的等宽字体(Consolas等)，依然不能对齐：
![console](https://github.com/clyoudu/clyoudu-util/blob/master/screenshot/console.PNG?raw=true)
将控制台的字符串复制到文本编辑器中，设置成包含中英文字符集的等宽字体，可以对齐：
![console](https://github.com/clyoudu/clyoudu-util/blob/master/screenshot/sublime.PNG?raw=true)

**Comment by 553234736** [comment]
thanks~

**Comment by ziang-info** [comment]
Great.
